// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xeckdgqnzyabdzrrreve.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhlY2tkZ3FuenlhYmR6cnJyZXZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NjUxMzQsImV4cCI6MjA2MDE0MTEzNH0.hR1Gd7WTJxw_94zayM39p2SZlIqsWS5FAvNlav6QfP8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);